### ISSUE TITLE
Copy Name Of Active File doesn't work under Linux (Virtual Box or VNC)

### ISSUE THREAD

**Issue by Selemia** [sleistner/vscode-fileutils#107]
Hello,

I'm using Visual Studio Code v1.33.1 and File Utils in three different ways:
- Directly under Windows 7 Enterprise: Copy Name Of Active File works like a charm.
- On a Debian 9.8 running in a Virtual Box VM: Copy Name Of Active File doesn't work, nothing is copied in the Clipboard.
- Connected to a Red Hat Enterprise 7.5 VM with a VNC client: Copy Name Of Active File doesn't work, nothing is copied in the Clipboard.

VS Code native commands "Copy Path" and "Copy Relative Path" work well in the three different ways.

Thanks to help me with this problem.

**Comment by sleistner** [comment]
This issue should have been addresses in #130

**Comment by Selemia** [comment]
The "Support remote development" patch in the 2.14.6 release is working like a charm.
Thanks for that.
