### ISSUE TITLE
Directory selector no longer displays

### ISSUE THREAD

**Issue by haberdashPI** [sleistner/vscode-fileutils#109]
Event with `"fileutils.typeahead.enabled": true`, the directory selector does not display. Seemed to start happening with newest VSCode version (???). There is a slightly longer delay when this parameter is set to `true`. I tried uninstalling and reinstalling the plugin, but that didn't seem to change anything.

- VSCode Version: 1.33.1
- OS Version: Mac OS X 10.11, 10.14 (tried on two different machines).

**Comment by pomdtr** [comment]
I did encounter the same issue, but only on the command fileutils.newFileAtRoot or fileutils.newFolderAtRoot

**Comment by sleistner** [comment]
The directory selector not showing for `fileutils.newFileAtRoot` or `fileutils.newFolderAtRoot` is the intended behaviour.
It should preselect the root folder of the current workspace.

It shouldn't be too hard to implement it differently, but I'm not sure about the use case.

Ideas welcome.

**Comment by pomdtr** [comment]
My goal is to be able to quickly create a new file (or directory) in any location of my project. So the directory should not be limited to the location of the file i'm currently editing.
I was previously able to do it with the command `fileutils.newFileAtRoot`, which was presenting me a list of all the directory available in my project.

I'm currently using the extension [advanced-new-file](https://marketplace.visualstudio.com/items?itemName=patbenatar.advanced-new-file) to reproduce this behaviour, the gif on their README is a good illustration of my use case

**Comment by haberdashPI** [comment]
My wishes are similar to those of @pomdtr. Using this plugin, I used to be able to ask to create a new file and then specify where within my project that file would be created. Something about the behavior seems to have changed with a recent update: `advanced-new-file` seems to be what I am looking for.

**Comment by sleistner** [comment]
Alright, understood. Trying to get working on it in the next days.
