### ISSUE TITLE
Add some commands to the Tab context menu 

### ISSUE THREAD

**Issue by WiliTest** [sleistner/vscode-fileutils#116]
**Is your feature request related to a problem? Please describe.**
I would love having the command found in the control palette inside the tab menu.  

**Describe the solution you'd like**
When right clicking on the tab menu, I would like to be able to:
+ Rename the file
+ copy it's name
+ delete it

Thanks already for your awesome work!

**Comment by WiliTest** [comment]
Awesome, thanks for doing it (and that  fast !)

There is just 2 little issue:
● when I click on "delete" from the tab menu, it takes about 5-10 seconds to get the popup (the delay seems to accur only the first time, after I start my computer, I guess there is nothing you could  do for that. Not the big deal though)

● The popup message when we delete a file is great, but it would be nice to indicate the full path of the file that will be deleted.
It's needed when we have 2 files open with the same filename (especially because the file that will be deleted, is the one in the active tab and not the one with the tab I right clicked on it* - the tab of the file we right click doesnt become the active file). I know this is not caused by your extension but by the way VSCode works. It's confusing when we come from other text editor (it's the same thing with copy name and rename).

**Comment by WiliTest** [comment]
Thank you, the rename seems to work now!

But the the `delete` and `rename` don't show on the context menu
![image](https://user-images.githubusercontent.com/24194840/58945968-2b65c200-8785-11e9-99dd-fd8abd29ce8e.png)

**Comment by sleistner** [comment]
Yes those were removed on purpose, more details here: #121

**Comment by WiliTest** [comment]
Thanks for your work Sleistner!
But unfortunately, your patch did not solve the rename issue (I still encounter the same problem describes above). 

(Concerning the removal, I commented it in  #122)

**Comment by WiliTest** [comment]
Thanks for your work Sleistner!
But unfortunately, your patch did not solve the rename issue (I still encounter the same problem describes above ―my CPU was maybe less busy when I tried the last time and told you it was working). 

(Concerning the removal, I commented it in  #122)

**Comment by sleistner** [comment]
> But unfortunately, your patch did not solve the rename issue
The remaining feature (for the time being) is `Copy Name`, are you referring to that command?
