### ISSUE TITLE
Customizing the commands

### ISSUE THREAD

**Issue by MagTun** [sleistner/vscode-fileutils#119]
**Is your feature request related to a problem? Please describe.**
In short : Being able to customize the commands 

For instance, I would like to add this command in "editor/context":

```
				{
					"command": "fileutils.copyFileName",
					"group": "1_copypath"
				}
```

I can do that by editing `C:\Users\Me\.vscode\extensions\sleistner.vscode-fileutils-2.14.4\package.json` but then on the next update I will loose my edits. 

**Describe the solution you'd like**
That would be great to be able to add the command in the settings file `C:\Users\user\AppData\Roaming\Code\User\settings.json` or anywhere else.

**Comment by sleistner** [comment]
Might not be the perfect solution but I guess it will partially solve your problem.
see #265
