### ISSUE TITLE
Copy file name output "敒污挠摮瀠瑥瑩灟潲牧浡挮摭"

### ISSUE THREAD

**Issue by WiliTest** [sleistner/vscode-fileutils#120]
Issue Type: <b>Bug</b>

When I click on "copy name" on the context menu of the tab, it output: 敒污挠摮瀠瑥瑩灟潲牧浡挮摭 (which seems to mean, "Stained and scratched". It's a kind of good joke though)

Extension version: 2.14.4
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sleistner** [comment]
Unfortunately I'm unable to reproduce the error, I checked with macOS 10.14 and Windows 10.
Someone else having a similar behavior?

**Comment by WiliTest** [comment]
Thanks again for your reply Sleistner. Sorry I should have taken more time to troubleshoot it. 

The problem is the delay which occur not only at the first use after reloading VScode, but also each time I change the tab. 

When I right click on a file tab and copy the name it doesnt do anything (so it past whatever was stored in the clipboard, like chinese stuff...*). After about 30 second it start to works, but only on this tab. If I switch to another tab, the same problem (occur: it does't copy the name for a while).  I guess my CPU isn't as fast as yours, and doesn't handle the file name quick enough.

*But* it works as expected (no delay) using "copy path" (or relative path). The code you use to retrieve the full path is more efficient than the one needed to retrieve the file name. 

(*ps: so the chinese stuff was irrelevant, it was probably stored in my clipboard by another bug that has nothing to do with vscode)
