### ISSUE TITLE
Rename file less (unsaved) editor

### ISSUE THREAD

**Issue by duianto** [sleistner/vscode-fileutils#125]
This extension is called `File Utils` with emphasis on `File`, but it would be useful if it also could rename a file less (unsaved) editor, for example: `Untitled-5`

It seems to work as expected until one tries to confirm the new name.
1. press: `ctrl + shift + p`
2. type: `rename` to highlight `File: rename`
3. press: `return`
4. the `New Name` input box appears with the current name selected: `Untitled-5`
5. but when a new name is typed, for example: `test`
6. when `return` is pressed, then nothing happens.

If it's outside the scope of this extension, or if vscode doesn't allow extensions to rename file less editors, then step 3 probably should show a warning message that only a saved file can be renamed.

**Comment by sleistner** [comment]
As there hasn't been any user feedback I am going to close this issue.
