### ISSUE TITLE
"File: duplicate" doesn't work on SSH remote

### ISSUE THREAD

**Issue by nicooprat** [sleistner/vscode-fileutils#126]
**Describe the bug**
The `File: duplicate` command has no effect when using remote VScode: https://code.visualstudio.com/docs/remote/remote-overview

**To Reproduce**
1. Open a file
2. CMD+SHIFT+P
3. `File: duplicate`
4. Enter a new file name
5. Nothing happens

**Expected behavior**
The file should be duplicated and opened.

**Screenshots**

**Desktop (please complete the following information):**
- VSCode Version: Version 1.36.0-insider (1.36.0-insider)
- OS Version: Mac 10.13.6 (17G65)

**Additional context**
This doesn't work using contextual menu in file explorer either.
I can't find any error message anywhere in VScode about this.

Thanks in advance!

**Comment by iliashkolyar** [comment]
Hey @nicooprat,
I'm using remote VScode via the official VSCode 1.35.1 version, and "duplicate" works properly for me.

Did you install the extension inside the SSH extensions section?
When opening the Extension pane, you'll now have 3 sections:

- SSH (Will only appear in SSH sessions)
- Local
- Recommended

The extension should be installed in the "SSH" section for it to work properly via remote.
If that is indeed the case, I suggest checking whether it works on latest official VScode (as mentioned above, 1.35.1 works for me). 
Maybe it's an Insiders issue..

**Comment by nicooprat** [comment]
Hi, the extension is installed in the SSH section. Other commands work anyway, like new file, delete file, ...

I'm using `Debian GNU/Linux 8 (jessie)` on my server, could it be an incompatibility issue? How could I see any error message in the extension?

Thanks.

**Comment by iliashkolyar** [comment]
Not sure regarding the error messages (don't think there are any relevant ones either way).
Did you try it on the latest VScode stable version?

**Comment by nicooprat** [comment]
Alright, it's working in the stable version. Didn't know it was already available in this channel. Sorry, thanks for your quick answer!
