### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rbadapanda** [sleistner/vscode-fileutils#127]
- Issue Type: `Bug`
- Extension Name: `vscode-fileutils`
- Extension Version: `2.14.5`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.37.0-insider`

Note: The following was reported by vscode > running extensions command

```json 
{
	"messages": [
		{
			"type": 2,
			"message": "`title/context` is not a valid menu identifier",
			"extensionId": {
				"value": "sleistner.vscode-fileutils",
				"_lower": "sleistner.vscode-fileutils"
			},
			"extensionPointId": "menus"
		}
	],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 271,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onCommand:fileutils.renameFile"
	},
	"runtimeErrors": []
}
```

**Comment by sleistner** [comment]
Thanks. Is that output from `Log (Extension Host)`?

**Comment by rbadapanda** [comment]
no.
in vsCode, use a fileutil command like for ex: new file or new folder.

Press F1, search for "running extensions"

in the report, Look for a line with file utils

**Comment by sleistner** [comment]
Unfortunately I am unable to reproduce the error. 
On the other hand `title/context` is not configured.
Thank you for pointing it out, let's keep an eye on that.
