### ISSUE TITLE
Error: command 'fileutils.duplicateFile' not found

### ISSUE THREAD

**Issue by seanfuture** [sleistner/vscode-fileutils#128]
**Describe the bug**
File: Duplicate command returns error: "command 'fileutils.duplicateFile' not found" when using the latest version of VS Code Insiders ( version details below ).  Tried uninstalling and reinstalling the extension which did not resolve the issue.

**To Reproduce**

1. Show all commands by pressing cmd + shift + p
2. Choose File: Duplicate
3. See error at the bottom right

**Expected behavior**
It duplicates the selected file.

**Screenshots**
![](https://user-images.githubusercontent.com/22125998/49073803-338cf400-f26e-11e8-8758-cb9770346e67.png)

![](https://user-images.githubusercontent.com/22125998/49073802-32f45d80-f26e-11e8-9769-5b9f8142664a.png)

**Desktop (please complete the following information):**
- VSCode Version:  1.37.0-insider
- OS Version:  Darwin x64 18.2.0

**Additional context**

- VSCode Version: 1.37.0-insider
- VSCode Commit: 3802a986823977ec472fc993854e1a753037fc8f
- Date: 2019-07-29T05:27:38.167Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.2.0

**Comment by sleistner** [comment]
Unfortunately I'm unable to reproduce the incident using the latest version of VSCode Insider.
Can you confirm the error still happens using the latest build?
 
```
Version: 1.37.0-insider
Commit: 1e3cc1a30d4fec3f4744e403e534f84c9b645217
Date: 2019-08-02T00:00:44.850Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by seanfuture** [comment]
Thank you kindly for attempting to reproduce.  It turns out in the end that a different extension installed, which was incompatible with the latest version of VSCode, was throwing an Exception that was then blocking other extensions / commands from registering.  After disabling that extension, vscode-fileutils worked fine.  Thank you - I believe this issue is now closed.
