### ISSUE TITLE
Remote WSL: "File: duplicate" command does not work

### ISSUE THREAD

**Issue by wongjn** [sleistner/vscode-fileutils#129]
**Describe the bug**
Using the "File: duplicate" command does not work. The following error is logged to dev tools:

```
ERR cb.apply is not a function: TypeError: cb.apply is not a function
	at /home/…/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/node_modules/graceful-fs/polyfills.js:287:18
	at FSReqWrap.oncomplete (fs.js:155:5)
```

**To Reproduce**
1. Open a file in VSCode WSL
2. Attempt to duplicate a file (via explorer context menu OR command palette)
3. Nothing happens, error in console.

**Expected behavior**
The file should be duplicated.

**Desktop (please complete the following information):**
- VSCode Version: 1.36.1
- OS Version: Windows 10 Pro 10.0.17763 Build 17763
- WSL Linux Distro: Ubuntu 18.04

**Comment by benjaminwood** [comment]
I believe this is a general remote development issue. I'm seeing the same behavior with [Remote - Containers](https://code.visualstudio.com/docs/remote/containers).
