### ISSUE TITLE
`New File Relative to Current View` shows nothing

### ISSUE THREAD

**Issue by garyking** [sleistner/vscode-fileutils#136]
**Describe the bug**

When choosing `File: New File Relative to Current View`, a dropdown of possible paths to choose from sometimes does not appear, even after waiting several minutes. This problem started happening a few days ago. The problem happens in workspaces where the problem previously did not exist. The CPU doesn't even increase to more than 10% for `Code Helper`, which would have indicated that it's at least doing something.

**To Reproduce**

1. Choose `File: New File Relative to Current View` in the command palette.
2. On the next page, it waits for results, while it says `First, select an existing path to create relative to`. But no results ever come.

**Expected behavior**

Results should appear.

**Screenshots**

![Dropdown options](https://user-images.githubusercontent.com/343940/63629260-2a536c80-c5df-11e9-8ddb-867c4e839626.png)

**Desktop (please complete the following information):**

- VSCode Version: Version: 1.37.1
- OS Version: MacOS 10.14.6 (18G87)

**Comment by pomdtr** [comment]
Same problem with NewFileAtRoot on Mac OS.

**Comment by sleistner** [comment]
Thanks for the report. 
Does the root directory contain many files and directories?

**Comment by pomdtr** [comment]
The command did trigger on a simpler project with fewer directories.

**Comment by pomdtr** [comment]
I also usually work in a container thanks to vscode remote, but I don't think the issue is related to this.

**Comment by sleistner** [comment]
I suspect the treewalker implementation to struggle with large directory structures.

I'm going to address the issue this week.

**Comment by pomdtr** [comment]
Hey, thanks for the quick response !

Unfortunately the filepicker now autoclose when i launch it on large repository

**Comment by sleistner** [comment]
I'm testing with a structure of `11111` nested directories and `99995` files without running into any issue. What kind of directory size/structure are you working with?

I figured that the bottleneck is somewhere with `node-glob`, but haven't found a reliable pattern to reproduce yet.

**Comment by pomdtr** [comment]
```sh
$ find .  -type d | wc -l
> 790
$ find .  -type d | wc -l
> 6590
```

I don't think the number of directory or file is the issue

**Comment by pomdtr** [comment]
I could try on Ubuntu to see if this is an os related issue.

**Comment by sleistner** [comment]
@garyking, @pomdtr 
Would you like to volunteer installing this beta version manually and provide feedback of how it behaves on your system?

_Beta version:_
https://github.com/sleistner/vscode-fileutils/releases/tag/3.0.0-beta

_Applied changes:_
https://github.com/sleistner/vscode-fileutils/pull/141

_Further instructions on how to install extensions manually:_
1. Open Visual Studio Code and select View->Extensions from the menu to display the Extensions pane.
2. Click the ... at the top-right corner of the Extensions pane and select "Install from VSIX..." on the menu that appears.
3. Locate the downloaded .vsix file and click "Open".
4. Visual Studio Code will prompt you to restart to enable the extension. Click "Restart" to confirm.

Make sure the installed version has changed to `3.0.0-beta`.

Thank you very much!

**Comment by pomdtr** [comment]
I did try the try the beta version of the extension but it did not resolve the issue on my machine

**Comment by sleistner** [comment]
@pomtdr has there been any error message popped up? Or something in the developer console?

**Comment by pomdtr** [comment]
![image](https://user-images.githubusercontent.com/17577332/63940189-46389180-ca69-11e9-8454-5d942d8061dc.png)

**Comment by sleistner** [comment]
@pomdtr Thanks, is it happening only with this particular workspace or with any directory of decent size?

**Comment by pomdtr** [comment]
The problem did occur in two workspace. One of them is fairly big, but the other one is not that important (but run inside a container).

**Comment by sleistner** [comment]
Can you confirm that the problem occurs with any workspace as long as it runs in a container?

**Comment by pomdtr** [comment]
Not sure about that, and since my internship terminated last week, i do not have access to the computer and the repository anymore :disappointed:

**Comment by sleistner** [comment]
no probs, thanks anyways

**Comment by garyking** [comment]
The problem occurs even with not run in a container.

**Comment by sleistner** [comment]
I'm trying to find a pattern as I'm unable to reproduce the problem.
Is there anything which is worth to mention, or which sets your setup apart?

**Comment by garyking** [comment]
I only experience the problem in one workspace, and for files in one folder only. If I copy this project to another place, then open the copy, then the problem does not occur.

So maybe the problem is fixed, but I'm still experiencing it for a handful of dirs, because VSC is caching something for those dirs?

**Comment by garyking** [comment]
Do you know how I could clear this VSC cache, so that I can hopefully fix this issue in these problematic dirs?

**Comment by garyking** [comment]
Any ideas on how to make `New File Relative to Current View` work in all workspaces? It's still not working in some of mine.

**Comment by sleistner** [comment]
Sorry, I still haven't been able to detect a pattern. I need to investigate more.

**Comment by garyking** [comment]
I'm still having this problem.

**Comment by garyking** [comment]
Still having this problem.
