### ISSUE TITLE
Skipping prompt in fileutils.newFile?

### ISSUE THREAD

**Issue by franciscolourenco** [sleistner/vscode-fileutils#150]
**Is your feature request related to a problem? Please describe.**
When I want to create a new file, I always get prompted where I want to create it. 

**Describe the solution you'd like**
I would like to create it by default adjacent to the file which is open, without being prompted twice. If I would like a different location, I can manipulate the pathname in the second prompt which asks for the filename.

**Describe alternatives you've considered**
This could be implemented in a new command, like `fileutils.quickNewFile`.

**Additional context**
First (redundant) prompt, which I would like to skip:
![image](https://user-images.githubusercontent.com/208149/67687907-4c7bb900-f999-11e9-9d6f-9225cd9a6ca1.png)

Second (useful) prompt:
![image](https://user-images.githubusercontent.com/208149/67687901-4a195f00-f999-11e9-8c0d-955d2282a592.png)

**Comment by sleistner** [comment]
Hi @franciscolourenco,

if you set `fileutils.typeahead.enabled` to `false` it should disable the directory selector.

https://github.com/sleistner/vscode-fileutils#configuration

Let me know if that works for you.

**Comment by franciscolourenco** [comment]
Hi @sleistner it works. Somehow I missed this option. Thanks!!!

**Comment by adamreisnz** [comment]
Can't believe the default behaviour is not actually set to false, I was bugged by this for ages!
