### ISSUE TITLE
Error creating files and directories using Insiders build

### ISSUE THREAD

**Issue by bhrutledge** [sleistner/vscode-fileutils#156]
**Describe the bug**
In the latest VS Code Insiders build, I get an error message whenever I run a variant of "New File" or "New Folder".

**To Reproduce**
1. Open a directory with VS Code Insiders , e.g. `code-insiders Downloads/`
2. Run "New File Relative to Project Root"
3. Enter `/Users/brian/Dropbox (Personal)/test.md`
4. See error: "Unable to delete non-existing file '/Users/brian/Downloads/test.md'"

Same behavior with "... Current View" and "New Folder ..."

**Expected behavior**
New tab created for `test.md` as in stable version of VS Code (currently 1.41.1)

**Desktop (please complete the following information):**
- VSCode Version:
    - Version: 1.42.0-insider
    - Commit: 5e758c10c969d668730f036abfc557d9cfb62b87
    - Date: 2020-01-13T09:41:37.825Z
- OS Version: macOS 10.15.2 (19C57)

**Comment by sleistner** [comment]
This issue seems to be a duplicate of #153

**Comment by bhrutledge** [comment]
Thanks!
