### ISSUE TITLE
"File: New Folder Relative to Current View" Invoked When Editing Keyboard Settings Causes Tons of Excess Memory/CPU to be Used

### ISSUE THREAD

**Issue by macintacos** [sleistner/vscode-fileutils#166]
**Describe the bug**

I was editing some keyboard shortcuts and wanted to see what would happen when I executed the "File: New Folder Relative to Current View" action from the Keyboard Shortcut editor view. Almost immediately, VSCode began to consume memory and CPU, and made my fans spin up like crazy.

This is reliably reproducible; probably because the keyboard settings are located in the user folder or something?

**To Reproduce**
1. Go to the Keyboard Shortcuts editor.
2. Invoke the "File: New Folder Relative to Current View" action.
3. Notice your fans spin up.

**Expected behavior**
VSCode wouldn't go crazy and consume all memory/CPU; ideally, this command would notice that you're trying to create a folder that is in a very high level folder and throw up an "Are you sure?" dialog of some sort.

**Screenshots**

Screenshots of iStat Menus showing memory/cpu usage shortly after invoking the action:

![image](https://user-images.githubusercontent.com/8128941/75124536-d86acc80-567d-11ea-87df-5fe98509fbe4.png)

![image](https://user-images.githubusercontent.com/8128941/75124538-dd2f8080-567d-11ea-8f10-b9a7d11db477.png)

**Desktop (please complete the following information):**

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by macintacos** [comment]
I originally opened this issue here: https://github.com/microsoft/vscode/issues/91252 but realized that this was a command provided by File Utils and not VSCode itself.

**Comment by sleistner** [comment]
Is this still an issue?

**Comment by macintacos** [comment]
@sleistner I was just about to note that it was still an issue, but glad to see it was addressed in #269 :) I'll give that a spin and open a new issue if I see encounter any problems.

**Comment by sleistner** [comment]
@macintacos its not yet released, travis runs a bit slow day. Once released it will be announced by semantic release’ bot.
