### ISSUE TITLE
Can't get keyboard shortcuts to work on Mac

### ISSUE THREAD

**Issue by Eiskis** [sleistner/vscode-fileutils#19]
- VSCode Version: 1.13
- OS Version: 10.12.5

This extension (which is awesome!) works as expected in the sidebar context menu and in the quick commands panel (for the currently active file), but I can't get the commands to work from the keyboard. I want to set keyboard shortcuts to move or duplicate the current file in the exact same way as the command palette option does.

Here is my `keybindings.json`:
```json
[
    {
        "key": "ctrl+shift+cmd+m",
        "command": "fileutils.duplicateFile"
    },
    {
        "key": "ctrl+cmd+m",
        "command": "fileutils.moveFile"
    }
]
```

With these bindings, I also see the appropriate shortcut in the command palette as expected, but when I press the keyboard shortcuts, nothing happens. I've tried:

- Different keyboard shortcuts, with no success.
- Removing all other keybindings to ensure there are no conflicts, with no success.
- Adding `when` option to the commands, with no success.
- Changing the command string to something else. In this case I get a warning that command is not found, leading me to believe that both the keybinding itself and the command string is correct, since with the above settings I get no warning (instead nothing happens when I activate the shortcut).

I'm not sure if these are even supposed to work since there are no default bindings, and this isn't mentioned in the README. Is there a way to get these to work, and is this a common issue?

**Comment by Eiskis** [comment]
Fast update! I think it broke things though.

After updating, this is what I get when using the commands from command palette:

<img width="845" alt="screen shot 2017-06-12 at 09 45 57" src="https://user-images.githubusercontent.com/1101002/27023714-0ce56b52-4f54-11e7-8830-1f0d84097d41.png">

And this is what I get when using the commands from keyboard:

<img width="846" alt="screen shot 2017-06-12 at 09 45 44" src="https://user-images.githubusercontent.com/1101002/27023715-0ce9ce90-4f54-11e7-8ec6-98fce78bbed8.png">

So, I get some kind of reaction from the keyboard shortcuts, but neither works now. Not sure what's up.

**Comment by sleistner** [comment]
Thanks, surely my fault. Tests were green, even on Travis.
Not sure how travis managed to not fail with missing Bluebird dependencies...

**Comment by Eiskis** [comment]
Yup, works now! Thanks for the quick fix.

The end-user experience with VS Code is pretty impressive btw, great platform to work on when updates are so effortless.
