### ISSUE TITLE
Do not highlight extension when renaming a file

### ISSUE THREAD

**Issue by mafredri** [sleistner/vscode-fileutils#2]
Most of the time when renaming a file, there is no need to change the extension, in this case I think it would make renaming smoother if only the name part of the file was highlighted.

Example: Instead of ![](https://www.dropbox.com/s/xjppbpyxqnqd5mr/Screenshot%202016-07-22%2013.31.49.png?dl=1) do ![](https://www.dropbox.com/s/sp36yzyb332nm76/Screenshot%202016-07-22%2013.32.13.png?dl=1).

There could be some edge cases, e.g. dotfiles (think `.editorconfig`). In these cases I think it would be fine to consider that they do not have an extension, and thus the full name would be highlighted.

**Comment by sleistner** [comment]
It is definitely something which should be supported, unfortunately I was not able to find a proper way of defining a selection.
I need to investigate how a selection can be specified in an input box.

**Comment by ayoubgdah** [comment]
+1
Thanks for the plugin.
Also for Duplicate, could be better to have only the filename highlighted. Most of the time you want to duplicate in the same location or some few levels up.
