### ISSUE TITLE
Add "Rename file" context menu option to open tab 

### ISSUE THREAD

**Issue by wellu** [sleistner/vscode-fileutils#210]
Using command palette is cumbersome so add **Rename file...** option to the context menu which opens when user right clicks on a tab of an open file.

**Comment by aoyama-val** [comment]
**Rename** is in the context menu on editor. BTW, I need **Delete** in the context menu.

**Comment by wellu** [comment]
Add it to the **tab** context menu.

![image](https://user-images.githubusercontent.com/2076593/87941445-d62d6280-caa3-11ea-9dab-7a723aa6a7c3.png)

**Comment by sleistner** [comment]
Thanks for bringing this up.
Since this #260 recent change we are finally equipped with everything we need to add more commands to editor and editor tab context menus.
