### ISSUE TITLE
Display context menu always full size

### ISSUE THREAD

**Issue by jmaguirrei** [sleistner/vscode-fileutils#219]
When right-clicking an item near the bottom of the sidebar, the context menu is shown with scrolling option.

![Screen Shot 2020-07-22 at 17 53 08](https://user-images.githubusercontent.com/11958637/88232931-bd0fe780-cc44-11ea-9eca-4239401e0be1.png)

Almost always I need to do the scrolling before reaching the desired option.

It would be nice to have the window always full-size to avoid scrolling waste of time and also have always the same expectation about the menu that appear when the item is clicked.

![Screen Shot 2020-07-22 at 17 53 21](https://user-images.githubusercontent.com/11958637/88232968-ce58f400-cc44-11ea-84ef-b2c6a1ea26f6.png)

Thanks

**Comment by sleistner** [comment]
This issue should be raised at vscode, I believe it can't be controlled via an extension.
