### ISSUE TITLE
`Could not open vscode-remote` in WSL2 after using duplicate option from FileUtlis

### ISSUE THREAD

**Issue by kanlukasz** [sleistner/vscode-fileutils#258]
**Describe the bug**
I work with WSL2 on my Windows 10 machine.
While I use the duplicate feature, I get the following notification:
```
cannot open vscode-remote://wsl%2Bubuntu-20.04/var/www/path/to/dir.
Detail: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/var/www/path/to/dir'
(Error: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/var/www/path/to/dir' that is actually a directory)
```
I'm not sure if this is a plugin issue or a VM side permission issue, but the message is from your plugin:
![obraz](https://user-images.githubusercontent.com/30685349/96873399-2afec180-1475-11eb-831d-e1084cdab806.png)

**To Reproduce**
1. Run any project on WSL2
2. Click on 'Duplicate' any directory
3. See error

**Expected behavior**
The error should not occur

**Desktop (please complete the following information):**
```
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by kanlukasz** [comment]
**Update:**
From what i see from `3.3.0` release, now it works fine again.
Have you changed anything?

**Comment by sleistner** [comment]
I haven’t changed anything intentionally to tackle this particular problem, but maybe one of the recent changes have caused a lucky side effect ;)

Glad it has been solved.
