### ISSUE TITLE
Command 'File Utils: Delete' resulted in an error - command not found

### ISSUE THREAD

**Issue by mikehazell** [sleistner/vscode-fileutils#267]
**Describe the bug**

All "File Util" commands result in an error like this:

```
Command 'File Utils: Delete' resulted in an error (command 'fileutils.removeFile' not found)
```

**To Reproduce**
1. Open any file
2. Invoke a File Utils command from the command pallet - eg: "File Utils: Delete"
3. The above error is shown

**Screenshots**

![image](https://user-images.githubusercontent.com/814227/97122746-55ee5b80-177c-11eb-98a4-6b477b74db9f.png)

**Desktop (please complete the following information):**
- VSCode Version: 1.50.1
- OS Version: Mac OS 10.15.7
- File Utils version: v3.3.1

**Comment by mikehazell** [comment]
Looks like this issue was introduced in v3.2.0

Rolling back to version `v3.1.1` has resolved the issue for me.

**Comment by sleistner** [comment]
Good catch @mikehazell 👍
