### ISSUE TITLE
Implement the bash/touch's multiple creation. {js,css,ts}

### ISSUE THREAD

**Issue by halilcakar** [sleistner/vscode-fileutils#279]
**Is your feature request related to a problem? Please describe.**
I'm really appreciate this extension and use it for while now. So recently I started working with React ecosystem and saw that lots of people using css seperatly and create files such as: 

`src/Card.js` and also `src/Card.css`.

**Describe the solution you'd like**
Therefor when u want to create a component lets say `Card` you need to create your JS file and then CSS file after. So I thought it would be nice to have a way to create these files together like when we use bash you can practicly do:

`touch src/Card.{jsx,css}`

As probably you know, this creates 2 files inside `src` directory.

I'm guessing for the people use to use these kinda commands on bash, this would be a nice addition to fileutils.

**Comment by sleistner** [comment]
Hi @halilcakar thats a splendid idea!

**Comment by halilcakar** [comment]
I actually though about making a PR for this but i've never actually worked with vscode-extensions so If you give me a small guide i could also follow through and make the changes

**Comment by sleistner** [comment]
Oh sorry, didn't see you message before I worked on the PR.
