### ISSUE TITLE
Command File Utils: New Folder at Root not found

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [sleistner/vscode-fileutils#284]
The side bar entry "New folder at Root" (and the relative one) fail to run, not opening the dialog to specify the path

**To Reproduce**

1. On the side bar, right click "New file relative to project root" (or folder)

**Expected behavior**
Open the dialog to specify the path and proceed with the normal flow

**Screenshots**
![failed_newfile](https://user-images.githubusercontent.com/1329559/98484983-1d14a480-21c8-11eb-8275-04981f669c0f.jpeg)

**Desktop (please complete the following information):**
- VSCode Version: 1.51.0
- OS Version: Ubuntu 18.04 LTS

**Comment by sleistner** [comment]
Thanks @Fire-Dragon-DoLgood catch, the build step didn't include `node_modules`. A patch is on its way.

**Comment by Fire-Dragon-DoL** [comment]
Thanks for the fast fix!
