### ISSUE TITLE
Duplicate file is not working. Not in File Explorer, not in open editor, nowhere.

### ISSUE THREAD

**Issue by Blum** [sleistner/vscode-fileutils#286]
**Describe the bug**
Duplicate file is not working. Not in File Explorer, not in open editor, nowhere.

**To Reproduce**
1. Open a file.
2. Open command palette, select File Utils: Duplicate; 
3. See error: Command 'File Utils: Duplicate' resulted in an error (command 'fileutils.duplicateFile' not found)

**Expected behavior**
Do duplicate the file in the same folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/31083/99041527-c4f8ec00-2593-11eb-8b84-81ed4c0bbf8c.png)

**Desktop (please complete the following information):**
- VSCode Version: 1.50.1
- OS Version: Arch Linux (recent)

**Comment by yakubenko** [comment]
The same here.

Maybe this output will help. It appears when I try to duplicate a file via the content menu.

`[2020-11-13 13:42:26.427] [exthost] [error] Activating extension sleistner.vscode-fileutils failed due to an error:
[2020-11-13 13:42:26.429] [exthost] [error] Error: Cannot find module 'brace-expansion'`

**Comment by sleistner** [comment]
Hi, thanks for the report.
This problem was fixed here https://github.com/sleistner/vscode-fileutils/issues/284

Could you please check if you use the latest version `v3.4.1`?

**Comment by yakubenko** [comment]
Thanks. Just upgraded to the latest version and all seems to be working as expected.

**Comment by sleistner** [comment]
Glad it worked out!

**Comment by t-fritsch** [comment]
@sleistner thanks for the fix but could you please publish latest version on open-vsx (used by vscodium) https://open-vsx.org/extension/sleistner/vscode-fileutils is still on version 3.4.0 ?

**Comment by Blum** [comment]
I'm also unable to update it, it just stays on 3.4.0, no matter what I do (uninstall, install, even changed DNS :grimacing:).

**Comment by yakubenko** [comment]
> I'm also unable to update it, it just stays on 3.4.0, no matter what I do (uninstall, install, even changed DNS grimacing).

In case you use Codium you just need to download it and install manually. It is available here https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils

That would be nice to have it on open-vsx as @t-fritsch has already asked for.

**Comment by Blum** [comment]
Thank you

**Comment by sleistner** [comment]
done. didn't even know about open-vsx.

**Comment by t-fritsch** [comment]
thanks a lot @sleistner !
