### ISSUE TITLE
Renaming a file closes the old (sometimes) and opens a new file

### ISSUE THREAD

**Issue by mafredri** [sleistner/vscode-fileutils#3]
Would it be possible to make renaming work like in the explorer? The explorer renames a file whilst keeping the editor window open. `fileutils` seem to close the file and open a new one. This has at least three consequences:

1. If a file is modified, it will be left open, and a new file with the new name will be opened
    * The explorer prompts the user to save or discard the contents, which is quite good behaviour in my opinion
2. The opened file will not be fully opened (e.g. it is opened in a "preview"-mode where opening another file will open it on top of this one).
3. Cursor position in file is lost

**Comment by sleistner** [comment]
As far as I understand the `vscode` api, there is currently no access to the underlaying `FileService` provided.

I created a ticket https://github.com/Microsoft/vscode/issues/9641

**Comment by mafredri** [comment]
Alright, looking forward to seeing how this develops. Thanks for investigating! :)

**Comment by sleistner** [comment]
Currently not supported it seems. Lets see what upcoming vscode versions will add...

**Comment by mafredri** [comment]
Bummer :(, maybe one day!
