### ISSUE TITLE
Use command with explorer context

### ISSUE THREAD

**Issue by jemmyphan** [sleistner/vscode-fileutils#30]
- VSCode Version: 1.19.1
- OS Version: OSX 10.13.2

Steps to Reproduce:

1. Use keyboard to navigate to desired explorer list
2. Run command ( ex: Rename)
3. It prompts to rename active file instead of focused file from explorer list.

is it intended behaviour? or it just works on active file only.

**Comment by sleistner** [comment]
At the moment, the command executed operates on the current file buffer only.
Explorer list commands can only be triggered using the context menu.
