### ISSUE TITLE
Batch rename feature?

### ISSUE THREAD

**Issue by kachkaev** [sleistner/vscode-fileutils#32]
It'd be great to batch rename files and folders with `vscode-fileutils`! The UI could be inherited from the VSCode's built-in _search and replace_ feature.

[muCommander](https://github.com/mucommander/mucommander) can also be a source of inspiration here. Its bulk rename is not ideal, but it does the job!

<img width="1121" alt="screen shot 2018-02-19 at 11 44 04" src="https://user-images.githubusercontent.com/608862/36376250-5552ff26-156a-11e8-83e3-90cdda9e2a2f.png">

<img width="863" alt="screen shot 2018-02-19 at 11 46 22" src="https://user-images.githubusercontent.com/608862/36376304-874d87d0-156a-11e8-8c7f-3f696c0aeb1f.png">

What muCommander can't do though is renaming files in subfolders. This may be useful, for instance, for converting a JavaScript project into a TypeScript one. 

Related StackOverflow question: https://stackoverflow.com/questions/44223988/how-to-rename-multiple-files-in-vscode-visual-studio-code

**Comment by felipegtx** [comment]
This would be awesome to have!

**Comment by janhesters** [comment]
Any progress on this?

**Comment by sleistner** [comment]
I'm not sure if this FR would be worth a dedicated extension. WDYT?
