### ISSUE TITLE
Not working with latest vs code version

### ISSUE THREAD

**Issue by camilosw** [sleistner/vscode-fileutils#35]
- VSCode Version: 1.20.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

Use any command. For example, New File Relative to Project Root return the error command 'fileutils.newFileAtRoot' not found.

I uninstalled and installed file utils, and restarted vs code and problem persist. Tried also with different projects.

**Comment by prashanth1k** [comment]
Same problem in Windows.
I am new to this extension - can't confirm whether it was working earlier.

VSCode version: 1.20.1
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS: Windows 10

Steps to reproduce issue:
Choose any command in Ctrl + P.
Error message displayed: 
`command 'fileutils.duplicateFile' not found`

**Comment by sleistner** [comment]
@camilosw & @prashanth1k 
Thank you guys for the immediate report, it wasn't covered by the tests unfortunately.
