### ISSUE TITLE
Plugin does not work at all.

### ISSUE THREAD

**Issue by harpreetsb** [sleistner/vscode-fileutils#357]
I am on ubuntu 20.04 with vscode
```
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:11.840Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-44-generic
```
keep getting errors:
`Command 'File Utils: Rename' resulted in an error (command 'fileutils.renameFile' not found)` 
for every command

**Comment by sleistner** [comment]
hi @harpreetsb , which extension version do you use?

**Comment by harpreetsb** [comment]
`v3.4.5`

**Comment by harpreetsb** [comment]
bump

**Comment by sleistner** [comment]
Could you please have a look into developer tool and check if there is any output?
We have tried with your version of the extension and Linux, but unfortunately we are unable to reproduce the defect.

**Comment by harpreetsb** [comment]
![Screenshot-20210323124859-608x373](https://user-images.githubusercontent.com/6584304/112108451-38f87000-8bd6-11eb-83df-64eae46a4f78.png)
from console

**Comment by sleistner** [comment]
Have you tried re-installing the extension?

**Comment by harpreetsb** [comment]
Yes i did that, same issue.

**Comment by sleistner** [comment]
@alexsavio could you give us a hand here?

**Comment by sleistner** [comment]
Anyone else encountering such problems?

**Comment by harpreetsb** [comment]
Ok I tried this,
- uninstalled the extension 
- closed VSCODE (previsously did not do this step)
- reinstalled extension
Works fine again
