### ISSUE TITLE
show the current dir path

### ISSUE THREAD

**Issue by rickmed** [sleistner/vscode-fileutils#4]
(Amazing extension).

It would be useful to show the dir path on the bar you are in (relative to the workspace). So you can delete, type/autocomplete on the bar while navigating.

**Comment by sleistner** [comment]
for a concrete command or in general?

**Comment by rickmed** [comment]
when you are in "browsing" mode (as opposed to when you select a specific command). In "browsing" mode the command palette is empty so it is a great opportunity to fill it with the relative (to the workspace) dir the files that are showing are. Additionally, you could browse through the folders, using that relative path (deleting and adding paths). Akin to this atom package. https://atom.io/packages/advanced-open-file

**Comment by rickmed** [comment]
@sleistner I'm soo sorry! I confused this extension with another very similar one I'm using.

Big apologies! Sorry again for the confusion and time waste.
