### ISSUE TITLE
Delete Command not Working on Mac

### ISSUE THREAD

**Issue by zcysxy** [sleistner/vscode-fileutils#462]
The command `File Utils: Delete` is not working on macOS. After executing this command, nothing happens. Also, when right-click a file in the sidebar explorer and click `delete`, a warning comes up

<img width="307" alt="image" src="https://user-images.githubusercontent.com/48207708/159116244-7b4f8637-0c72-4485-b27a-9fbd361f0660.png">

- VSCode Version: 1.65.2 (Universal)
- OS Version: macOS Monterey 12.3
- FileUtils Extension Version: v3.5.0

**Comment by sleistner** [comment]
Hi @zcysxy could you please confirm if that issues persists?

**Comment by zcysxy** [comment]
@sleistner It's gone!
