### ISSUE TITLE
show quickpick menu for file move instead of using text input

### ISSUE THREAD

**Issue by ctf0** [sleistner/vscode-fileutils#478]
**Is your feature request related to a problem? Please describe.**
- not really but atm the move file is an input based "where u type the path u want to move the file to" not a quick picker item "where u get a quick picker menu to choose from the new path"

**Describe the solution you'd like**
- something similar to this would be very helpful [REF: file-bunny](https://github.com/robole/file-bunny)
![move-file](https://user-images.githubusercontent.com/7388088/169628197-8a71da7a-12d7-4ab4-862d-3446c389d213.gif)

**Comment by sleistner** [comment]
how about moving and preselect that folder to the very top below `workspace root`?

**Comment by ctf0** [comment]
> how about moving and preselect that folder to the very top below `workspace root`?

also would it be possible to represent the directories as menu & sub menus, instead of the current ?

**Comment by sleistner** [comment]
could you provide an example?

**Comment by ctf0** [comment]
> could you provide an example?

like the gif at the top, so instead of having something like `src\nested\path` (the current), you only see `src` and when entered you then only see the directories under it.

**Comment by ctf0** [comment]
another example https://github.com/ctf0/vscode-quick-file-browser

**Comment by sleistner** [comment]
Thank you, that's great feedback, appreciated.
