### ISSUE TITLE
Commands are not found after version 3.5.1

### ISSUE THREAD

**Issue by edgarjs** [sleistner/vscode-fileutils#492]
**Describe the bug**
Commands are no longer found after version 3.5.1

**To Reproduce**
1. Open the command palette
2. Search for any of the FileUtils command (e.g. 'Duplicate')
3. See error

**Expected behavior**
Commands should be found and available.

**Screenshots**
<img width="274" alt="20230111134253" src="https://user-images.githubusercontent.com/12443/211902751-783e4d3a-806b-42b4-8a7b-106de41016b4.png">

**Desktop (please complete the following information):**
- VSCode Version: 1.74.3
- OS Version: Darwin arm64 21.6.0 (Monterey 12.6.2)
- FileUtils Extension Version: 3.5.1

**Comment by sleistner** [comment]
Thanks @edgarjs, version `3.5.2` has been published which should fix the issue.
