### ISSUE TITLE
Option to open the newly created file

### ISSUE THREAD

**Issue by rickmed** [sleistner/vscode-fileutils#5]
Many times you would want to edit the newly created file. So would be nice an option (settings) to open the file immediately after it is created.

**Comment by sleistner** [comment]
indeed, that is the intended behavior. on which OS you're experiencing the issue?

**Comment by rickmed** [comment]
vscode 1.4, windows10 x64

**Comment by sleistner** [comment]
Unfortunately I'm not able to reproduce the issue running windows 10 x64, vscode 1.4 on virtualbox.
Could you open the Developer Tools and check if an error has been thrown?

```
Help => Toggle Developer Tools => Console
```

**Comment by rickmed** [comment]
No errors in the console. 

After a hit enter after typing the file name, it gets created but it is not opened.

**Comment by sleistner** [comment]
I assume `vscode-fileutils` version is >= `2.0.1`?

**Comment by rickmed** [comment]
@sleistner I'm soo sorry! I confused this extension with another very similar one I'm using.

Big apologies! Sorry again for the confusion and time waste.
