### ISSUE TITLE
File: Create New File Relative to Current View does not work anymore

### ISSUE THREAD

**Issue by 8** [sleistner/vscode-fileutils#50]
- VSCode Version: 1.24.0
- OS Version: Win10

Steps to Reproduce:

1. Open a file
2. execute the Command "File: Create New File Relative to Current View"

Expectation:
Get asked for the file name to create, like in the previous version.

What happens instead:
A popup that asks: "First select an existing path to create relative to"
Which makes no sense, as it should be created to the currently open file.

The extension just autoupdated and broke. 
Is there a page with older versions so that I can go back to a working version in the meantime?

Thank you!

Take care,
Martin

**Comment by sleistner** [comment]
Hi Martin,

indeed the behaviour seems odd, it is kind of intended though as requested in #48.
You could set `"fileutils.typeahead.enabled": false` in order to disable the feature.

Best
Steffen

**Comment by sleistner** [comment]
How would you expect the feature to work? Ideas welcome.

**Comment by sleistner** [comment]
I changed the behaviour slightly:

Directory relative to current view contains nested directories?
1. yes => show quick pick => select nested dir => show new file name input 
2. no => show new file name input

**Comment by 8** [comment]
Thank you for the quick reply!

Disabling:
```
"fileutils.typeahead.enabled": false
```
solves the problem for me!

I haven't tried out the new feature yet - so I cannot comment on the behavior yet. I will read it up and return later. Thanks already!

Take care,
Martin
