### ISSUE TITLE
remove some useless menu when click workspace

### ISSUE THREAD

**Issue by tjx666** [sleistner/vscode-fileutils#537]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/41773861/226460041-929c2d12-dac6-48f8-9a4e-55d2434fbbac.png">

You can use the `explorerResourceIsRoot` context key in when cluase like following:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226460255-2243e416-39a7-480c-a115-a2bbf9850390.png">

Versions:

```
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```

**Comment by sleistner** [comment]
Thank you @tjx666. Which context menus do you consider useless and why?

**Comment by tjx666** [comment]
close because I think they may all has use case now.
