### ISSUE TITLE
Move to top Yes when deleting a file

### ISSUE THREAD

**Issue by rickmed** [sleistner/vscode-fileutils#6]
Avoid enter, down, enter. Just enter, enter.

**Comment by sleistner** [comment]
like having `Yes` preselected?

**Comment by rickmed** [comment]
Yes. Currently, "No", is preselected.

**Comment by sleistner** [comment]
Just to be sure, you talk about the information message with `Yes` and `Close` buttons?
![](https://monosnap.com/file/BZU7EX4j8IeP0TJrIVSlTWtPj5ijJN.png)

If so, I think there is currently no API to preselect a specific message item.

https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.showInformationMessage

**Comment by sleistner** [comment]
In the long run I would like to replace the message box by a native conform dialog as it is used from vscode internal code in the file tree browser.

Unfortunately most of the internal services such as file service etc. are currently not accessible from 3rd party extensions.

**Comment by rickmed** [comment]
@sleistner I'm soo sorry! I confused this extension with another very similar one I'm using.

Big apologies! Sorry again for the confusion and time waste.

**Comment by sleistner** [comment]
@rickmed out of curiosity, how is the other extension called?

**Comment by rickmed** [comment]
https://marketplace.visualstudio.com/items?itemName=jakelucas.code-file-nav#review-details
