### ISSUE TITLE
How to add file utils commands to the context menu?

### ISSUE THREAD

**Issue by WiliTest** [sleistner/vscode-fileutils#60]
- OS Version: windows 10

I'm struggling to understand where I should add [file utils commands](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils#overview
) to the context menu. Could you please tell me where I should paste these commands:

```
{
    "explorer/context": [
        {
            "command": "fileutils.moveFile",
            "group": "edit"
        },
        {
            "command": "fileutils.duplicateFile",
            "group": "edit"
        }
    ],
    "editor/context": [
        {
            "command": "fileutils.moveFile",
            "group": "edit"
        },
        {
            "command": "fileutils.duplicateFile",
            "group": "edit"
        }
    ]
}
```
Thanks !

**Comment by sleistner** [comment]
@WiliTest they'll just appear in the context menu, no need to add them anywhere.
<img width="603" alt="screenshot 2018-10-08 at 09 30 15" src="https://user-images.githubusercontent.com/12568/46596450-dd58cb80-cadc-11e8-953c-438708cd6d82.png">
<img width="485" alt="screenshot 2018-10-08 at 09 30 29" src="https://user-images.githubusercontent.com/12568/46596451-dd58cb80-cadc-11e8-95db-2577f151479a.png">

**Comment by WiliTest** [comment]
[solved]
Thanks a lot for your quick reply!
I was trying to click the tab name (as I do in np++ or atom), not within the file in the editor or in the file explorer. Your screenshot helped me. Thanks!

**[feature request]:** it would be nice to be able to use the move, delete, rename on the context menu when we click on the title.
