### ISSUE TITLE
Can we configure the context menu? 

### ISSUE THREAD

**Issue by saelfaer** [sleistner/vscode-fileutils#7]
- VSCode Version: 1.6.0
- OS Version: Linux Mint

Can we configure the context menu of the file panel?
I'd love to add duplicate file on the context menu on a file.

**Comment by sleistner** [comment]
In the file explorer next to `Move`?

**Comment by saelfaer** [comment]
I was more asking if it was configurable somewhere. can we open a settings file and add that command to a new context menu item,. or does it need to be added here in the plugin itself?

if so, yeah somewhere around move would be logically the best place.

**Comment by sleistner** [comment]
need to see the docs if dynamic contributes are supported, nevertheless it could be statically added next to `Move`

**Comment by sleistner** [comment]
#8 done
