### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by brnmonteiro** [sleistner/vscode-fileutils#78]
**Describe the bug**
Is not find fileutils command

**To Reproduce**
1. Just go to File: Rename
2. See error

**Expected behavior**
Rename a file

**Screenshots**
![captura de tela 2018-11-14 as 16 34 32](https://user-images.githubusercontent.com/6596579/48504152-337f0400-e82b-11e8-92db-af1a3af3c442.jpg)

**Desktop (please complete the following information):**
- VSCode Version: 1.22
- OS Version: Mac OS Mojave 10.14

**Comment by sleistner** [comment]
I'm unable to reproduce the issue, not on MacOS not on Windows/Ubuntu.

Can you provide the developer tools output when calling the command?

**Comment by michaelnguyen547** [comment]
@brnmonteiro try to use the latest visual code 1.29. I used 1.23 and had the same problem. Upgrade to 1.29 fixed the issue

**Comment by brnmonteiro** [comment]
> @brnmonteiro try to use the latest visual code 1.29. I used 1.23 and had the same problem. Upgrade to 1.29 fixed the issue

Worked! Thanks!

**Comment by Blum** [comment]
This is happening again to me. VSCode 1.51.1

**Comment by sleistner** [comment]
@Blum which version of the extension?

**Comment by Blum** [comment]
Hello, v3.4.0.

**Comment by sleistner** [comment]
@Blum did you try updating to version v3.4.2?

**Comment by sleistner** [comment]
there was a problem with v3.4.0 https://github.com/sleistner/vscode-fileutils/compare/v3.4.0...v3.4.1

**Comment by sleistner** [comment]
I have just reinstalled the extension, which installed v3.4.2
Could you please try uninstall and install again?
