### ISSUE TITLE
Autocomplete paths when creating a new file

### ISSUE THREAD

**Issue by kevdotbadger** [sleistner/vscode-fileutils#9]
I think this would be a great addition.

**Comment by sleistner** [comment]
You're absolutely right that would be a great addition, unfortunately content manipulation of input boxes are currently not supported by vscode.

Hope at some point there will be an vscode API change, until then I have to put you request on hold.

https://github.com/Microsoft/vscode/issues/426

**Comment by muhajirframe** [comment]
https://github.com/patbenatar/vscode-advanced-new-file . It seems like this plugin does have the autocomplete feature. Take a look at the gif.

I myself haven't tried yet. I am typing on phone. Will try it later.

**Comment by sleistner** [comment]
@muhajirframe interesting concept, I'll have a look, thank you.

**Comment by siran** [comment]
Yes, please, without tab-completition is a burden to move typing the full path
